#!/bin/sh

. /lib/functions.sh

USER_SECTION=""
USER_EXISTS=0

find_user(){
	local section="$1"
	local user="$2"
	config_get username $section username
	if [ "$username" == "$user" ]; then
		USER_SECTION="$section"
		USER_EXISTS=1
	fi
}

config_load rpcd

USER_EXISTS=0
config_foreach find_user login root
if [ $USER_EXISTS -eq 1 ]; then
	uci delete rpcd.$USER_SECTION
fi

USER_EXISTS=0
config_foreach find_user login admin
if [ $USER_EXISTS -eq 0 ]; then
	uci -q add rpcd login >/dev/null
	uci -q set rpcd.@login[-1].username="admin"
	uci -q set rpcd.@login[-1].password="\$p\$admin"
	uci -q add_list rpcd.@login[-1].write="user-admin"
	uci -q add_list rpcd.@login[-1].write="juci-broadcom-iptv"
	uci -q add_list rpcd.@login[-1].write="juci-wifilife"
	uci -q add_list rpcd.@login[-1].write="juci-wireless"
	uci -q add_list rpcd.@login[-1].write="juci-wireless-admin"
	uci -q add_list rpcd.@login[-1].write="juci-catv"
	uci -q add_list rpcd.@login[-1].write="juci-broadcom-pwrmgmt"
	uci -q add_list rpcd.@login[-1].write="juci-ddns"
	uci -q add_list rpcd.@login[-1].write="juci-diagnostics"
	uci -q add_list rpcd.@login[-1].write="juci-domos"
	uci -q add_list rpcd.@login[-1].write="juci-ndt"
	uci -q add_list rpcd.@login[-1].write="juci-dnsmasq-dhcp"
	uci -q add_list rpcd.@login[-1].write="juci-dropbear"
	uci -q add_list rpcd.@login[-1].write="juci-dropbear-keymanagement"
	uci -q add_list rpcd.@login[-1].write="juci-ethernet"
	uci -q add_list rpcd.@login[-1].write="juci-event"
	uci -q add_list rpcd.@login[-1].write="juci-firewall-fw3"
	uci -q add_list rpcd.@login[-1].write="juci-icwmp"
	uci -q add_list rpcd.@login[-1].write="juci-igmpinfo"
	uci -q add_list rpcd.@login[-1].write="juci-backup"
	uci -q add_list rpcd.@login[-1].write="juci-multiwan"
	uci -q add_list rpcd.@login[-1].write="juci-qos"
	uci -q add_list rpcd.@login[-1].write="juci-voice-client"
	uci -q add_list rpcd.@login[-1].write="juci-voice-client-ca"
	uci -q add_list rpcd.@login[-1].write="juci-minidlna"
	uci -q add_list rpcd.@login[-1].write="juci-mcproxy"
	uci -q add_list rpcd.@login[-1].write="juci-easyqos"
	uci -q add_list rpcd.@login[-1].write="juci-mod-status"
	uci -q add_list rpcd.@login[-1].write="juci-mod-system"
	uci -q add_list rpcd.@login[-1].write="juci-mod-system-file"
	uci -q add_list rpcd.@login[-1].write="juci-mod-system-backup"
	uci -q add_list rpcd.@login[-1].write="juci-mod-system-upgrade"
	uci -q add_list rpcd.@login[-1].write="juci-mod-system-service"
	uci -q add_list rpcd.@login[-1].write="juci-mod-system-admin"
	uci -q add_list rpcd.@login[-1].write="juci-mwan3"
	uci -q add_list rpcd.@login[-1].write="juci-natalie-dect"
	uci -q add_list rpcd.@login[-1].write="juci-netmode"
	uci -q add_list rpcd.@login[-1].write="juci-network-device"
	uci -q add_list rpcd.@login[-1].write="juci-network-device-admin"
	uci -q add_list rpcd.@login[-1].write="juci-network-dsl"
	uci -q add_list rpcd.@login[-1].write="juci-network-dsl-admin"
	uci -q add_list rpcd.@login[-1].write="juci-network-netifd"
	uci -q add_list rpcd.@login[-1].write="juci-network-port"
	uci -q add_list rpcd.@login[-1].write="juci-openvpn"
	uci -q add_list rpcd.@login[-1].write="juci-owsd"
	uci -q add_list rpcd.@login[-1].write="juci-printer"
	uci -q add_list rpcd.@login[-1].write="juci-realtime-graphs"
	uci -q add_list rpcd.@login[-1].write="juci-samba"
	uci -q add_list rpcd.@login[-1].write="juci-sfp"
	uci -q add_list rpcd.@login[-1].write="juci-snmpd"
	uci -q add_list rpcd.@login[-1].write="juci-sysupgrade"
	uci -q add_list rpcd.@login[-1].write="juci-uhttpd"
	uci -q add_list rpcd.@login[-1].write="juci-upnp"
	uci -q add_list rpcd.@login[-1].write="juci-usb"
	uci -q add_list rpcd.@login[-1].write="core"
	uci -q add_list rpcd.@login[-1].write="juci-file"
	uci -q add_list rpcd.@login[-1].write="unauthenticated"
fi

USER_EXISTS=0
config_foreach find_user login user
if [ $USER_EXISTS -eq 0 ]; then
	uci -q add rpcd login >/dev/null
	uci -q set rpcd.@login[-1].username="user"
	uci -q set rpcd.@login[-1].password="\$p\$user"
	uci -q add_list rpcd.@login[-1].write="user-user"
	uci -q add_list rpcd.@login[-1].write="juci-broadcom-iptv"
	uci -q add_list rpcd.@login[-1].write="juci-wifilife"
	uci -q add_list rpcd.@login[-1].write="juci-wireless"
	uci -q add_list rpcd.@login[-1].write="juci-wireless-admin"
	uci -q add_list rpcd.@login[-1].write="juci-catv"
	uci -q add_list rpcd.@login[-1].write="juci-ddns"
	uci -q add_list rpcd.@login[-1].write="juci-diagnostics"
	uci -q add_list rpcd.@login[-1].write="juci-ndt"
	uci -q add_list rpcd.@login[-1].write="juci-dnsmasq-dhcp"
	uci -q add_list rpcd.@login[-1].write="juci-ethernet"
	uci -q add_list rpcd.@login[-1].write="juci-firewall-fw3"
	uci -q add_list rpcd.@login[-1].write="juci-igmpinfo"
	uci -q add_list rpcd.@login[-1].write="juci-voice-client"
	uci -q add_list rpcd.@login[-1].write="juci-minidlna"
	uci -q add_list rpcd.@login[-1].write="juci-mcproxy"
	uci -q add_list rpcd.@login[-1].write="juci-easyqos"
	uci -q add_list rpcd.@login[-1].write="juci-mod-status"
	uci -q add_list rpcd.@login[-1].write="juci-mod-system"
	uci -q add_list rpcd.@login[-1].write="juci-natalie-dect"
	uci -q add_list rpcd.@login[-1].write="juci-netmode"
	uci -q add_list rpcd.@login[-1].write="juci-network-device"
	uci -q add_list rpcd.@login[-1].write="juci-network-dsl"
	uci -q add_list rpcd.@login[-1].write="juci-network-netifd"
	uci -q add_list rpcd.@login[-1].write="juci-network-port"
	uci -q add_list rpcd.@login[-1].write="juci-printer"
	uci -q add_list rpcd.@login[-1].write="juci-realtime-graphs"
	uci -q add_list rpcd.@login[-1].write="juci-samba"
	uci -q add_list rpcd.@login[-1].write="juci-sfp"
	uci -q add_list rpcd.@login[-1].write="juci-upnp"
	uci -q add_list rpcd.@login[-1].write="juci-usb"
	uci -q add_list rpcd.@login[-1].write="core"
	uci -q add_list rpcd.@login[-1].write="juci-file"
	uci -q add_list rpcd.@login[-1].write="unauthenticated"
fi

uci commit rpcd

